In [4]:
my_list=[1,2,3,4,5]


In [5]:
my_list

[1, 2, 3, 4, 5]

In [6]:
import numpy as np               # list into 1 D array using numpy

arr=np.array(my_list)

arr

array([1, 2, 3, 4, 5])

In [49]:
n=[[1,2,3],[4,5,6],[7,8,9]]

In [50]:
a1=np.array(n)                   # list into 2d array

a1                        # [[]] - indicates it is 2d list contains 3 rows and 3 columns.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# creating array using numpy:



np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
# creating arrays with elements using numpy:

np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))     # creates 2d array of 2 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
#linspace: it gives evenly spread points between start and end point.

np.linspace(0,10,5)            # here ) is start point and 10 is end point. 5 is number of equally space point we get between 0 to 10.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
# identity matrix:

np.eye(3)      # accepts only one argument 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
np.random.rand(5)       # create 1d array of random numbers with uniform distribution numbers between 0 to 1

array([0.76162312, 0.67572135, 0.77426794, 0.8823916 , 0.42226504])

In [8]:
np.random.rand(5,5)     # create 2d array of random numbers with uniform distribution numbers between 0 to 1

array([[0.82913374, 0.90550124, 0.22351049, 0.04737424, 0.20116142],
       [0.75025353, 0.12172336, 0.07698544, 0.45197236, 0.4346853 ],
       [0.89541724, 0.05762321, 0.48809512, 0.81894982, 0.27484808],
       [0.22789787, 0.91289693, 0.36572697, 0.19482711, 0.99831212],
       [0.97106287, 0.04445246, 0.8299504 , 0.24581699, 0.78418293]])

In [51]:
np.random.randn(2)         # get 2 std distribution near to 0 or write simple std distribution or gaussian distribution we use randn

array([-1.44178665,  0.50020351])

In [9]:
np.random.randn(4,4)

array([[ 0.40585852,  0.6589256 , -0.9745688 ,  0.78457775],
       [-1.67057117,  1.44947152, -0.73665783,  0.91260664],
       [ 2.05680281, -0.46491858, -1.32285048, -1.4192    ],
       [ 0.86277016,  0.15007737, -0.27035421,  0.5126571 ]])

In [14]:
np.random.randint(1,100)             # get random integer from 1 to 100

6

In [15]:
np.random.randint(1,100,7)          # get 7 random integers from 1 to 100

array([ 2, 38, 75, 27, 52, 42, 31])

In [16]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
arr=np.arange(25)        # creating array of 25 integers

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
arr1=np.random.randint(0,50,10)   # creating array of 10 random integers from 1 to 50

In [23]:
arr1

array([19,  2, 14, 11, 30, 48, 22, 13, 10, 31])

In [24]:
arr.reshape(5,5)          #reshaping arr to 2d array 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr1.reshape(5,2)

array([[19,  2],
       [14, 11],
       [30, 48],
       [22, 13],
       [10, 31]])

In [28]:
arr1

array([19,  2, 14, 11, 30, 48, 22, 13, 10, 31])

In [33]:
arr1.max()         # find max number in array

48

In [34]:
arr1.min()        # find min number in array

2

In [35]:
arr1.argmax()     # find index of max number  in array

5

In [36]:
arr1.argmin()    # find index of min number in array

1

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr.shape       # used to calculate shape of array

(25,)

In [39]:
arr=arr.reshape(5,5)

In [40]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.shape       # used to calculate shape of array i.e.5*5

(5, 5)

In [45]:
arr.dtype          # used to tell data type of array

dtype('int64')

In [46]:
from numpy.random import randint  # used to directly use randint or any method. 

In [48]:
randint(1,20,5)    #no need to initialization Required 

array([17, 18, 16, 16,  6])

In [52]:
array_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [53]:
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
array_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [55]:
array_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [56]:
array_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [57]:
array_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [76]:
array_2d[1:2,0:]

array([[20, 25, 30]])

# Numpy indexing and selection:


In [81]:
a1=np.arange(11,20)

In [82]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [83]:
a1[5]

16

In [84]:
a1[0:4]

array([11, 12, 13, 14])

In [85]:
a1[2:]

array([13, 14, 15, 16, 17, 18, 19])

In [86]:
a1[:5]

array([11, 12, 13, 14, 15])

In [90]:
a1[7:]

array([18, 19])

In [91]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [92]:
a1[0:5]=100

In [93]:
a1

array([100, 100, 100, 100, 100,  16,  17,  18,  19])

In [94]:
a1

array([100, 100, 100, 100, 100,  16,  17,  18,  19])

In [97]:
a1[0:5]=np.arange(11,16)

In [98]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [99]:
arr=a1

In [108]:
arr       # array slicing

array([100, 100, 100, 100, 100, 100,  17,  18,  19])

In [109]:
s1=arr[0:6]

In [110]:
s1

array([100, 100, 100, 100, 100, 100])

In [111]:
s1[:]

array([100, 100, 100, 100, 100, 100])

In [112]:
s1[:]=100

In [113]:
s1

array([100, 100, 100, 100, 100, 100])

In [114]:
arr           # here change in array slicing affects main array.

array([100, 100, 100, 100, 100, 100,  17,  18,  19])

In [115]:
# using copy method we can make chages in slicing of the array but main array remains same.

In [122]:
arr[0:6]=np.arange(11,17)

In [123]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [124]:
arr_copy=arr.copy()                     # copy array into arr_copy variable

In [125]:
arr_copy

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [129]:
arr_copy[:]=100                   # changes apply to arr_copy variable.

In [130]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100])

In [131]:
arr       # original array remains same for the process .

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

 # 2d array:

In [133]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [134]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
array_2d[1][1]          # double bracket format to access elements from array.

5

In [137]:
array_2d[0][1]

2

In [142]:
array_2d[1,2]         # single bracket format to access elements from array

6

In [143]:
array_2d[2,0]

7

In [147]:
array_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [156]:
array_2d[1:2,:3]

array([[4, 5, 6]])

# conditional selection:

In [2]:
arr=np.arange(1,11)

NameError: name 'np' is not defined

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr > 5          # gives boolean array

array([False, False, False, False, False])

In [9]:
bool_arr=arr>5

In [10]:
bool_arr

array([False, False, False, False, False])

In [11]:
arr[bool_arr]      # gives array of elements greater than 5.

array([], dtype=int64)

In [12]:
# or use:

arr[arr>5]

array([], dtype=int64)

In [13]:
arr[arr<5]

array([1, 2, 3, 4])

In [14]:
arr




array([1, 2, 3, 4, 5])