In [1]:
my_list=[1,2,3,4,5]


In [2]:
my_list

[1, 2, 3, 4, 5]

In [3]:
import numpy as np               # list into 1 D array using numpy

arr=np.array(my_list)

arr

array([1, 2, 3, 4, 5])

In [4]:
n=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
a1=np.array(n)                   # list into 2d array

a1                        # [[]] - indicates it is 2d list contains 3 rows and 3 columns.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# creating array using numpy:



np.arange(0,5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
# creating arrays with elements using numpy:

np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((2,3))     # creates 2d array of 2 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
#linspace: it gives evenly spread points between start and end point.

np.linspace(0,10,5)            # here ) is start point and 10 is end point. 5 is number of equally space point we get between 0 to 10.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
# identity matrix:

np.eye(3)      # accepts only one argument 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(5)       # create 1d array of random numbers with uniform distribution numbers between 0 to 1

array([0.74206675, 0.57965983, 0.01890656, 0.5880777 , 0.07728148])

In [17]:
np.random.rand(5,5)     # create 2d array of random numbers with uniform distribution numbers between 0 to 1

array([[0.93883825, 0.57529953, 0.28346482, 0.6769181 , 0.59017677],
       [0.3798039 , 0.01534166, 0.92936869, 0.60057957, 0.76736186],
       [0.18168465, 0.97927442, 0.75721292, 0.61564084, 0.64055623],
       [0.4752766 , 0.4882054 , 0.20496366, 0.47087337, 0.0930238 ],
       [0.96345366, 0.85939468, 0.05806597, 0.65047078, 0.04442758]])

In [18]:
np.random.randn(2)         # get 2 std distribution near to 0 or write simple std distribution or gaussian distribution we use randn

array([-1.39489105, -0.22461079])

In [19]:
np.random.randn(4,4)

array([[ 1.02231196, -0.39440476, -1.34817226, -1.34750305],
       [-0.00979763, -0.3269796 , -1.32845267,  1.56236598],
       [-0.72654693,  2.17750442,  0.9925201 ,  1.91895549],
       [-0.82049838, -0.55317542, -0.73788198, -2.33872109]])

In [20]:
np.random.randint(1,100)             # get random integer from 1 to 100

89

In [21]:
np.random.randint(1,100,7)          # get 7 random integers from 1 to 100

array([36, 37, 85, 70, 31, 51, 81])

In [22]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr=np.arange(25)        # creating array of 25 integers

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr1=np.random.randint(0,50,10)   # creating array of 10 random integers from 1 to 50

In [26]:
arr1

array([42, 49, 13,  0, 40, 20, 25, 22, 47, 15])

In [27]:
arr.reshape(5,5)          #reshaping arr to 2d array 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr1.reshape(5,2)

array([[42, 49],
       [13,  0],
       [40, 20],
       [25, 22],
       [47, 15]])

In [29]:
arr1

array([42, 49, 13,  0, 40, 20, 25, 22, 47, 15])

In [30]:
arr1.max()         # find max number in array

49

In [31]:
arr1.min()        # find min number in array

0

In [32]:
arr1.argmax()     # find index of max number  in array

1

In [33]:
arr1.argmin()    # find index of min number in array

3

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr.shape       # used to calculate shape of array

(25,)

In [36]:
arr=arr.reshape(5,5)

In [37]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.shape       # used to calculate shape of array i.e.5*5

(5, 5)

In [39]:
arr.dtype          # used to tell data type of array

dtype('int64')

In [40]:
from numpy.random import randint  # used to directly use randint or any method. 

In [41]:
randint(1,20,5)    #no need to initialization Required 

array([ 8, 16,  5, 18,  9])

In [42]:
array_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [43]:
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
array_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [45]:
array_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [46]:
array_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [47]:
array_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [48]:
array_2d[1:2,0:]

array([[20, 25, 30]])

# Numpy indexing and selection:


In [49]:
a1=np.arange(11,20)

In [50]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
a1[5]

16

In [52]:
a1[0:4]

array([11, 12, 13, 14])

In [53]:
a1[2:]

array([13, 14, 15, 16, 17, 18, 19])

In [54]:
a1[:5]

array([11, 12, 13, 14, 15])

In [55]:
a1[7:]

array([18, 19])

In [56]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [57]:
a1[0:5]=100

In [58]:
a1

array([100, 100, 100, 100, 100,  16,  17,  18,  19])

In [59]:
a1

array([100, 100, 100, 100, 100,  16,  17,  18,  19])

In [60]:
a1[0:5]=np.arange(11,16)

In [61]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
arr=a1

In [63]:
arr       # array slicing

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [64]:
s1=arr[0:6]

In [65]:
s1

array([11, 12, 13, 14, 15, 16])

In [66]:
s1[:]

array([11, 12, 13, 14, 15, 16])

In [67]:
s1[:]=100

In [68]:
s1

array([100, 100, 100, 100, 100, 100])

In [69]:
arr           # here change in array slicing affects main array.

array([100, 100, 100, 100, 100, 100,  17,  18,  19])

In [70]:
# using copy method we can make chages in slicing of the array but main array remains same.

In [71]:
arr[0:6]=np.arange(11,17)

In [72]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [73]:
arr_copy=arr.copy()                     # copy array into arr_copy variable

In [74]:
arr_copy

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [75]:
arr_copy[:]=100                   # changes apply to arr_copy variable.

In [76]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100])

In [77]:
arr       # original array remains same for the process .

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

 # 2d array:

In [78]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [79]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
array_2d[1][1]          # double bracket format to access elements from array.

5

In [81]:
array_2d[0][1]

2

In [82]:
array_2d[1,2]         # single bracket format to access elements from array

6

In [83]:
array_2d[2,0]

7

In [84]:
array_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [85]:
array_2d[1:2,:3]

array([[4, 5, 6]])

# conditional selection:

In [86]:
arr=np.arange(1,11)

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr > 5          # gives boolean array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [89]:
bool_arr=arr>5

In [90]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [91]:
arr[bool_arr]      # gives array of elements greater than 5.

array([ 6,  7,  8,  9, 10])

In [92]:
# or use:

arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [93]:
arr[arr<5]

array([1, 2, 3, 4])

In [94]:
arr




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])